### ISSUE TITLE
Emacs daemon

### ISSUE THREAD

**Issue by bkchr** [wbolster/emacs-direnv#11]
Hi, I currently start emacs as a daemon with systemd --user.
Do you ever tried that? Because when I do that, direnv does not work. I don't really understand why, maybe it missing some environment variables?

When I start emacs from my terminal, it works as expected (stopped the daemon before).

**Comment by wbolster** [comment]
what is the exact error you see?

check the troubleshooting section in the readme, you may want to look at the (hidden) `*direnv*` (with leading space in front) buffer for diagnostic output.

please share that info (anonimising is fine).

**Comment by bkchr** [comment]
When I switch into a project that has in some parent dir an .envrc, direnv loads something, but not all environment variables. It also does not complain, it just do not loads them..

**Comment by wbolster** [comment]
does the `*direnv*` buffer contain the json output with all the stuff that you would like to see there? can you share snapshots of relevant `*direnv*` buffer contents at various stages of your reproduction steps?

does it work in a shell?

**Comment by wbolster** [comment]
also, when you run this in a terminal:

```shell
cd  # go to home dir
(cd /path/to/your/project; direnv export json)
```

what do you see?

**Comment by bkchr** [comment]
I don't see the hidden buffer, I tried every way. (Using spacemacs)

Here is the direnv output:
https://pastebin.com/Zv6iecQL

**Comment by bkchr** [comment]
Okay, I found a way to open the buffer, sorry for the inconvenience!

So here first the output of the *direnv* buffer:
https://pastebin.com/e1a6TBfr

And here in the terminal:
https://pastebin.com/Sz0BZ1jg

There are cleary some variables missing(e.g. RUST_SRC_PATH). I'm using Nixos, maybe it is the operation system. I will also try to check for further bugs.

**Comment by wbolster** [comment]
there are no errors so emacs-direnv seems to behaving fine, so i think this has to do with your setup.

does your shell config initialise env vars in `.bashrc` and so on? (this is the setup many people including me use.)

you may want to give [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) a try. relevant snippet from my own `init.el`:

```
(use-package exec-path-from-shell
  :config
  (setq exec-path-from-shell-check-startup-files nil)
  (exec-path-from-shell-initialize))
```

**Comment by wbolster** [comment]
also try reading up on how things like `~/.profile`, `~/.bash_profile` and `~/.bashrc` interact. it is a complicated mess and there seems no single right answer.

i think your systemd user service that starts emacs runs with an incomplete environment because it does not load some of the config files in which env vars are set.

**Comment by bkchr** [comment]
I solved the problem! Thanks for your help!

I used /bin/sh -c "emacs --daemon" to start the daemon, but normally I use zsh as my shell. So I changed the command to use zsh and it works.

Again, thanks for your good and fast help. :)

**Comment by wbolster** [comment]
nice, enjoy your improved emacs experience! let me know if you have ideas for improvements of this package.

thanks for leaving a positive comment, i appreciate that a lot.

**Comment by bkchr** [comment]
Yeah I let you know!

I really like the plugin and especially in conjunction with Nixos, it's perfect :)
