### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by bandresen** [wbolster/emacs-direnv#14]
This project is currently lacking a clearly stated free license.

Please consider adding one. :-)

Reference: https://github.com/emacsmirror/epkg-reports/blob/master/licenses-details.org

**Comment by wbolster** [comment]
there is one very clearly stated in the readme:

https://github.com/wbolster/emacs-direnv#license

i guess i need to put it elsewhere? (do you know where?)

**Comment by wbolster** [comment]
@bandresen i assume that adding a "License" header to the source file suffices, and i added that in d181475. please let me know if this is not enough.

**Comment by bandresen** [comment]
Oh don't worry it was my fault. I was checking several packages and fell for it not being stated in the source file itself.

Thanks for making it more explicit!

**Comment by wbolster** [comment]
ok, thanks for confirming!
