### ISSUE TITLE
Opening a new M-x shell fails sometimes

### ISSUE THREAD

**Issue by glasser** [wbolster/emacs-direnv#18]
When I open a new shell with M-x shell in a direnv-controlled directory, I sometimes find that my DIRENV_DIR/DIRENV_DIFF/DIRENV_WATCHES are set in the shell but the actual env vars I'm trying to set aren't set.

Specifically, the env vars are properly set in emacs in the buffer (ie M-: `(getenv "PATH")` shows the right value) but `echo $PATH` in the shell doesn't work.

If neither my env vars nor the DIRENV_ vars were set, then direnv itself would just run and fix things, which would be fine.  But instead we end up in a place where direnv thinks everything is fine but the vars aren't set.

I can easily fix it with `direnv reload` but this is annoying!

**Comment by wbolster** [comment]
could this be some nasty interaction between shell configuration vars and the environment that emacs uses when it spawns a shell?

**Comment by glasser** [comment]
Maybe?

**Comment by wbolster** [comment]
fwiw #24 is eshell related

**Comment by glasser** [comment]
Cool, though M-x shell is not the same thing as Eshell.

**Comment by wbolster** [comment]
this is potentially explained by this comment: https://github.com/wbolster/emacs-direnv/issues/16#issuecomment-646136149
