### ISSUE TITLE
`direnv-edit` doesn't work.

### ISSUE THREAD

**Issue by MalcolmChen** [wbolster/emacs-direnv#20]
`direnv-mode` works ok.
I can enabled and disabled it by `direnv-mode` with no errors.
but when i try to add more environment  variable  with command `direnv-edit`, Emacs  gives error:
`error in process filter: comint-output-filter: Symbol's function definition is void: dirtrack-filter-out-pwd-prompt`
`error in process filter: Symbol's function definition is void: dirtrack-filter-out-pwd-prompt`
`direnv edit: exited abnormally with code 1.`

And `C-h f` `dirtrack-filter-out-pwd-prompt` gives me nothing .
and I searched around for `dirtrack-filter-out-pwd-prompt`, and found a wiki which shows me how to custom define this function.
this is obviously neither what i want nor what I needed.
any suggestion i could solve this problem  ?

**Comment by wbolster** [comment]
not sure about the `dirtrack` stuff (that's not `direnv`), but in general `direnv-edit` has a few problems, so you'd be better off just editing `.envrc`, and running `direnv allow` (from a shell) afterwards.

**Comment by MalcolmChen** [comment]
Thanks for the quickly reply. guess I'm gonna give it up.
in fact , wht I need is just one environment variable `PYTHONPATH`.
and wht I do now to get it done is using `.dir-locals.el` file , and put content 
`((python-mode`
  `    (eval setenv "PYTHONPATH" "/path/to/project")))`
in it.

finally set variable `enable-local-eval ` to `t` --- which was told too danger.

I'm gonna waiting for you to make `direnv-edit` work as it suppose to be and quit that danger way , :).

**Comment by wbolster** [comment]
just put it in `.envrc` and run `direnv allow` from a shell. `emacs-direnv` will pick it up!

**Comment by wbolster** [comment]
i've completely removed the broken `direnv-edit` command fc36cb98bfc375358c249148ff0699bfe50fd434
