### ISSUE TITLE
Consider tagging a new release

### ISSUE THREAD

**Issue by ccharles** [wbolster/emacs-direnv#22]
[MELPA Stable][1] lets users install stable¹ versions of software that is available through MELPA. As a MELPA Stable user I have been happily using emacs-direnv; it greatly simplifies my workflow.

I recently stumbled across `direnv-non-file-modes`, introduced in [this commit][2]. Hoping to use it with [Magit][3] and [emacs-python-pytest][4], I tried to set it. Unfortunately, it is not present in the [most recent tagged release, version 1.2.1 from June, 2017][5] (the newest version available through MELPA Stable).

Assuming the code is relatively stable, please consider tagging a new release so MELPA Stable users can use `direnv-non-file-modes` and other new features.

Thank you for your hard work!

---
¹Tagged versions of software are considered stable.

[1]: https://stable.melpa.org/
[2]: https://github.com/wbolster/emacs-direnv/commit/80845b7a5da478514f2df90b09373e963bd785e1
[3]: https://magit.vc/
[4]: https://github.com/wbolster/emacs-python-pytest
[5]: https://github.com/wbolster/emacs-direnv/commit/3c632dd1fdf0ad1edb6d9b0a4a09cdbb420c27aa

**Comment by wbolster** [comment]
oops, i actually did bump the version 1.3.0 (and tag it) last week, for exactly the reason you described:
https://github.com/wbolster/emacs-direnv#history

turns out i forgot to push the tags to github, which i just did:

```
To github.com:wbolster/emacs-direnv.git
 * [new tag]         1.3.0 -> 1.3.0
```

the next melpa stable build should have it. this usually takes a few hours.

**Comment by wbolster** [comment]
anyway, since you're into `emacs-python-pytest` and `direnv-mode` (both of which i wrote), let me know how it goes since i'm eager to learn from others having similar workflows as i do. :)

**Comment by ccharles** [comment]
Thanks for the quick fix!

I didn't realize you also wrote `emacs-python-pytest`, but I guess that explains why its README references `direnv-mode` :smile:. I'll update my local package and try it out.

**Comment by wbolster** [comment]
heh. `direnv` is fantastic and solves all my ‘path problems’. i wanted that in emacs as well, hence `direnv-mode`. :deciduous_tree: 

and since `python-pytest.el` needs correct execution paths as well, i decided to put a recommendation in the readme.
