### ISSUE TITLE
Error with zlib that doesn't occur in `direnv`

### ISSUE THREAD

**Issue by karljs** [wbolster/emacs-direnv#27]
I recently started having a weird issue where `emacs-direnv` throws an error that doesn't occur in regular `direnv`.  The output from the `*direnv*` buffer is not very enlightening, but it looks related to zlib.  Any ideas?  Searching for this error leads to some old bug reports on Go, but I haven't been able to make any progress from there.

This happens on only one of my machines.  The offending machine runs Arch linux while the working one runs Ubuntu, so I imagine it's related to a particular version or package, perhaps?

```
direnv: error unmarshal() zlib opening: unexpected EOF
{
  "DIRENV_DIFF": "eJw0yl-XakAAAPDvMs_riFktztmHUawRF9MgXhzWdPOnVDSo03e_T_f99wJXoL_eH-AC9BfYYmL-ifMtJkAHgnjqz0xsi3sn_vYVE--sv47g479KEN3Y5h7ogDmLt_Ks27xB4cwtqJK5_jw3EbSHQbOU9cqbPQzjxmOK3B9ptZe1U8JqYcJ5rn1JQq0cw7gx3UeW0iXVwkGadu1tjoIrH4qSR-RA60diuM7sPgu0UX_6ifncWtEDL-fqeTsf1msm7fMOQ_pQSVSUHLd2oLR_izEV5GYclKCpM9PZyVvvOQ1kSBwrYhjWKMtghH6cS4rK3ZJKlEBVNgjE_qKgz4sd3EcYaqyvYjtwBf7l8y7wR7X7lZLQkJjmluWEEAry3KCSXKHvb_B-_wsAAP__9dxuUA==",
  "DIRENV_DIR": "-/home/karl/test",
  "DIRENV_WATCHES": "eJyM0MFqxCAQxvF38Rxi4mjU3Hss9F560MxMI3VjMe52ofTdS29hWei-wI__971-i5fQVjELuZYTyY9Qs1wKkqxUPpvsabvURXTiuWBLJxLzaAC8GoweOvF0TXvbxdzqmX66e1S_lI3Tu8RUabvIkHP5kgatY-2jts5PjiZEJK2DMzwsRsWJFUeI3iAZZ3UAGJnYAbKyY1TR382BR3IOy5A4nHPrt3Q9eodVHPL-v7OvlPOt8lc1WQB1e9LbbwAAAP__BT12dA=="
}
```

**Comment by wbolster** [comment]
never seen this, sorry.

perhaps it's a data problem, not a code problem.  if you start emacs from your home dir (no direnv i presume), then open a file in a dir with a minimal envrc (export FOO=bar), do you also see it?

also it seems there is still json output in your example. does emacs-direnv pick it up?  (setting "always show summary" config may help)

**Comment by karljs** [comment]
I'm pretty sure this is related to trying to use direnv's support for Nix and something in my Nix configuration.  After lots of changes coming from Nix and my own code I'm not able to reproduce this anymore, so I'll close it for now.

**Comment by wbolster** [comment]
ok, cool!
