### ISSUE TITLE
Summary not showing

### ISSUE THREAD

**Issue by phillord** [wbolster/emacs-direnv#29]
For me, the summary never shows in the mini-buffer.

I am not quite sure why I am getting this and (I presume) other people can see the message, but I think it's because somethign is blocking the redisplay. I'd suggest putting "(sit-for 0)" after the message form which normally does the trick!

**Comment by wbolster** [comment]
it definitely shows for me. is this for manual updates? what about direnv-mode? also are there any changes? try monitoring the hidden buffer to see actual direnv output. (see readme.)

**Comment by phillord** [comment]
No, I am using direnv mode. And, indeed, it works on a clean Emacs with just direnv installed. Even there, though there are problems. For example, open two python buffers one in a direnv controlled directory, one not. Now move backward and forward between the two. If you use `other-window' to do this, then it all works. But if you use the mouse, the direnv message flashes up and then disappears too quickly to read.

If memory serves me correctly, `post-command-hook' runs after re-display. Not quite sure yet what is removing your message but something is.

**Comment by wbolster** [comment]
perhaps you have another `post-command-hook` that runs after the hook that `direnv-mode` adds?

**Comment by phillord** [comment]
I checked that, but this wouldn't explain the behaviour in a clean emacs with the mouse.
