### ISSUE TITLE
Document minimum required version of direnv.

### ISSUE THREAD

**Issue by carrete** [wbolster/emacs-direnv#3]
Ubuntu 16.04 includes direnv version 2.7.0 but it seems as though 2.8.0 is required as emacs-direnv requires `direnv export json`, correct?

https://github.com/direnv/direnv/blob/master/CHANGELOG.md#280--2016-03-27

With 2.7.0, the error from emacs-direnv is:

    direnv--export: Error running direnv: exit code 1; output was:
    ""

However, from the command-line:

    $ direnv export json
    direnv: error Unknown target shell 'json'

I assume that's stderr and emacs-direnv only captures stdout.

Thanks for this package! It's long overdue.

**Comment by wbolster** [comment]
you are right, @carrete.

i have added a remark to the readme about this in commit bda0cc7.

unfortunately parsing the `direnv export bash` output is far from trivial, which is why this package depends on the json output (and hence direnv 2.8 or later).

**Comment by wbolster** [comment]
also, getting _both_ stdout and stderr into separate buffers is problematic in emacs <25, which explains why you do not see the stderr output.

fwiw, you can view the ` *direnv*` buffer (make sure to start with a space) to monitor the direnv output whenever direnv is triggered.

**Comment by wbolster** [comment]
(oh hi)

fwiw, changes from #8 and #10 make troubleshooting easier.

**Comment by carrete** [comment]
:+1:
