### ISSUE TITLE
Show messages from `.envrc` in Emacs

### ISSUE THREAD

**Issue by matthew-piziak** [wbolster/emacs-direnv#30]
Sometimes `direnv-update-environment` takes a while, and it would be nice to see `echo` messages from the `.envrc` in Emacs to see progress. Is this possible?

**Comment by wbolster** [comment]
the hidden ` *direnv*` buffer (with leading space) contains all direnv output, but it's only shown automatically if `direnv` exits with a non-zero exit code. this is typically enough to troubleshoot problems.

see also #31. closing this since #31 is similar (duplicate) but has a bit more details.
