### ISSUE TITLE
The post-command-hook will fail if the .envrc file isn't allowed

### ISSUE THREAD

**Issue by jvshahid** [wbolster/emacs-direnv#32]
When I open a file in a project whose `.envrc` wasn't whitelisted before, the [direnv--export](https://github.com/wbolster/emacs-direnv/blob/6cf079fe8171bdf4bebefe02e8353d7f13847ebd/direnv.el#L100) will error causing the post-command-hook to be removed.  I believe post-command-hooks that fail/error are removed.  This causes subsequent buffer switches not to trigger direnv hook.

I am not sure what's the best way to achieve this, but I applied the attached patch that replaces `error` with `message` locally and it seems to be working fine.

```patch
From 96e8c7a70f37167864a410bacad52950b31115b7 Mon Sep 17 00:00:00 2001
From: John Shahid <jvshahid@gmail.com>
Date: Fri, 15 Feb 2019 12:28:27 -0500
Subject: [PATCH] Replace error with message

Otherwise, direnv's post-command-hook could fail causing it to be removed from
the list.
---
 direnv.el | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/direnv.el b/direnv.el
index 7d6c135..6bd824f 100644
--- a/direnv.el
+++ b/direnv.el
@@ -97,8 +97,8 @@ In these modes, direnv will use `default-directory' instead of
              (exit-code (call-process "direnv" nil '(t t) nil "export" "json")))
         (unless (zerop exit-code)
           (display-buffer (current-buffer))
-          (error "Error running direnv: exit code %s; output is in buffer '%s'"
-                 exit-code direnv--output-buffer-name))
+          (message "Error running direnv: exit code %s; output is in buffer '%s'"
+                   exit-code direnv--output-buffer-name))
         (unless (zerop (buffer-size))
           (goto-char (point-max))
           (re-search-backward "^{")
-- 
2.20.1
```

**Comment by wbolster** [comment]
yes, your analysis is right. but i'm not convinced ignoring errors is the right thing to do. you will end up with an environment that does not match the expectations...

**Comment by jvshahid** [comment]
Sorry, I missed your reply earlier.  I agree, this isn't the best solution but it is better than remove the post command hook.  This leads to the same result, i.e. an environment that doesn't match the expectations on the next buffer change.  At least with this patch, emacs-direnv has a chance to run again.  I'm open to other suggestions on how to fix this issue.

**Comment by Profpatsch** [comment]
I have opened an upstream request to add this information to the json message: https://github.com/direnv/direnv/issues/467

Disabling the auto-switch it for every buffer when just one buffer is not allowed means it also breaks for every buffer where the `.envrc` works just fine. Once direnv returns a non-malformed json reply in that case, we can display an error in the user prompt when the user switches to the broken buffer, and keep the post-command-hook working enabled.

**Comment by jvshahid** [comment]
I'm not sure why the exit-code isn't sufficient in this case to let the user know that they need to run `direnv allow` ?
