### ISSUE TITLE
release 1.5.0

### ISSUE THREAD

**Issue by Profpatsch** [wbolster/emacs-direnv#39]
We’ve got a few changes in, should we do a new release? I think I updated the Changelog with everything relevant in my last PR.

**Comment by wbolster** [comment]
sure, i bumped the versions ini 8ad3672c56d65b1eacc012cc51a36ed544b4b160 and added a tag on top

**Comment by wbolster** [comment]
melpa unstable just tracks `master` so this is mainly of interest to those using stable melpa
