### ISSUE TITLE
Caching strategies

### ISSUE THREAD

**Issue by lassik** [wbolster/emacs-direnv#40]
Have you thought about having a buffer-local variable (e.g. `direnv--cached-environment`) which would be an association list of environment variables and their values. Its default value would be nil.

Any time that variable would be nil, emacs-direnv would run direnv in a sub-shell to get the envars. But if it were non-nil, emacs-direnv would trust the cached values in it and update `exec-path` and `process-environment` based on them.

I haven't (yet) used environment managers and don't know if this makes sense, but just a hunch.

**Comment by lassik** [comment]
Another option would be to have a global hash table mapping directory pathnames to their environment alists. This would avoid duplicate alists in files that are from the same directory. It would also transparently handle the case where a file is moved from one directory to another in dired while that file is open in a buffer. (The above buffer-local caching technique would be confused by that and keep using the environment from the old directory.)

In both cases there could be an explicit refresh command that the user could call, or refresh could be always done at intervals of 30 minutes, etc.

**Comment by wbolster** [comment]
`direnv-mode` is just one way of using this package. its goal is to always keep things in sync. caching seems to go against that goal.

`direnv-update-environment` is another way to use this package. it will modify the environment inside emacs once, and not automatically change anything until you invoke it again.

i'm not sure which problem you're trying to solve tbh, and whether this package is part of the solution :)

**Comment by lassik** [comment]
I wasn't trying to solve a concrete problem, just thinking out loud. I didn't realize you favor always being up-to-date over caching. It's a sound preference and if things are currently fast enough then there is no problem :)

**Comment by wbolster** [comment]
the technical complication is that direnv does not "set" the environment. it "transforms" it from one env to the other, including unsetting env vars. caching would complicate this a lot
