### ISSUE TITLE
direnv-mode tries to parse direnv errors

### ISSUE THREAD

**Issue by stribb** [wbolster/emacs-direnv#41]
I've been experiencing a direnv configuration error, beyond the scope of this report. (FYI, "direnv export json" is erroring out for me with:  Couldn't find a configuration directory for direnv)

When this happens, the problem is compounded by direnv--export trying to parse the stderr output. The symptom is that re-search-backward can't find "^{".

Does it make sense to refrain from parsing when exit-code is nonzero?

**Comment by wbolster** [comment]
hmmm, maybe. if the problem happens the exit code is nonzero, but maybe direnv will output _unsetting_ of variables if it came from another directory?

**Comment by stribb** [comment]
Okay, but arguably it should never try to parse stderr.

**Comment by wbolster** [comment]
correct. also, stderr is only inserted into the `*direnv*` buffer if the exit code is nonzero, which is also not ideal.

would you be comfortable trying to come up with a pull request to improve this?

**Comment by stribb** [comment]
How about I put the JSON-encoded stderr into *direnv* if there is any?

Yes, I'm just about comfortable with that level of elisp hacking.

**Comment by wbolster** [comment]
cool :+1: 

i think `stderr` is never json encoded, only stdout is. so i think this flow would work:

- run process, stdout goes into buffer
- if not empty, this should contain only json
- append a newline to the buffer
- insert stderr (could be empty, but no need to check for it)
