### ISSUE TITLE
Track previously set envvars, and unset them when loading a new direnv config

### ISSUE THREAD

**Issue by christianromney** [wbolster/emacs-direnv#5]
It would be nice when you detect a new direnv file (different from the active one) and are about to load it if you would unset the previous file's exports. This is one way to approximate direnv's normal unloading when you change out of a directory. This could prevent clashes and inconsistencies, because otherwise as you open several buffers, the environment within emacs will continue to accrete additional state that isn't easily understood by the end user.

**Comment by wbolster** [comment]
I think this already works since direnv keeps track of that. try opening a split window and open the hidden `*direnv*` (start with a space!) in one. than switch between files from different direnv dirs in the other window. you should see the output change. null values from the json are unset.

**Comment by christianromney** [comment]
How do the null values get unset? I'll test this out, to make sure, but it's great if they're already being unloaded!

**Comment by wbolster** [comment]
`(setenv)` in combination with the `null` values is supposed to take care of that:

> `(setenv VARIABLE &optional VALUE SUBSTITUTE-ENV-VARS)`
>
> Set the value of the environment variable named VARIABLE to VALUE.
> VARIABLE should be a string.  VALUE is optional; if not provided or
> nil, the environment variable VARIABLE will be removed.

**Comment by christianromney** [comment]
Brilliant!
