### ISSUE TITLE
Code actually requires Emacs 26.1

### ISSUE THREAD

**Issue by purcell** [wbolster/emacs-direnv#56]
Hi! `provided-mode-derived-p` was only added in Emacs 26.1, so you might like to bump the required Emacs version, or use a different formulation for that logic. FWIW, recent `package-lint` versions can detect this class of issues quite reliably.

**Comment by wbolster** [comment]
@purcell thanks. #59 should fix this.

old `package-lint` could not :) now it's warning-free again.
