### ISSUE TITLE
show a summary of changes after updating evironment

### ISSUE THREAD

**Issue by christianromney** [wbolster/emacs-direnv#6]
When changing a user's environment, the package tell the user in some way what envvars have been loaded or unloaded.

**Comment by wbolster** [comment]
good idea. how would this work with automatic updates via the minor mode?

**Comment by wbolster** [comment]
i noticed that you deprecated `projectile-direnv`. existing users of that one should not have any steps back when switching to this one.

i will add this feature, it makes a lot of sense. :)

stay tuned.

**Comment by wbolster** [comment]
i implemented this in 95cd08b95e5b5fcef7d517f40a8a334dd6c0fd97.

please try it out, and have a look at the updated readme.

feedback and ideas welcome!

**Comment by wbolster** [comment]
i have added nice colour support for the summary message, which is just so awesome that it is enabled by default. mandatory screenshot:

![image](https://cloud.githubusercontent.com/assets/748944/23811101/c82c40d0-05d4-11e7-8a79-74e1d80fa5cf.png)

/cc @christianromney any other features or behaviours from projectile-direnv that do not have an alternative that is at least as good in this package?

**Comment by christianromney** [comment]
@wbolster This looks great. For some reason `direnv--installed` isn't being set for me.
When I manually run `(executable-find "direnv")` it returns the correct path `"/usr/local/bin/direnv"`, but it's not set when I start emacs. If I explicitly `setq` it in my config, everything works perfectly. Great work!

**Comment by christianromney** [comment]
Can't wait for the faces enhancement to hit MELPA!

**Comment by wbolster** [comment]
@christianromney thanks for the kind words.

re. your intitlalisation issue: how do you start emacs? do you change `exec-path` upon startup, e.g. via [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)?

can you try to add

```emacs
(message "%s" exec-path)
```

at the top of your `init.el`, and also right before you load `direnv`, i.e. right above `(direnv-mode)` (if you use that and rely on the autoload). do those paths contain `/usr/local/bin/`?

manually setting `direnv--installed` is a hack (it's an internal variable after all).

the reason for the check is that not having direnv installed gives ugly errors in the `post-command-hook` that `direnv-mode` installs. i will add a warning when `direnv-mode` is enabled but `direnv` could not be found.

**Comment by wbolster** [comment]
@christianromney  fyi, in dd0b8c0c9d676a1672004a6a72faa398982d0579 i added "detect again" logic when direnv is not know to be installed when enabling `direnv-mode`. does that help?
