### ISSUE TITLE
*Warnings* buffer pops up when .envrc is blocked

### ISSUE THREAD

**Issue by rvl** [wbolster/emacs-direnv#60]
I often visit files in projects where `direnv` is not allowed.

I do not necessarily want to unblock `.envrc` for these projects.

In this case, the `*Warnings*` buffer keeps popping up with the error message from `direnv`.

Is there any way to prevent these warnings from appearing?

**Comment by rvl** [comment]
If `(warn ...)` were replaced with `(display-warning 'direnv ...)` then it would be possible to customize  `warning-suppress-log-types` to hide the warnings.

**Comment by wbolster** [comment]
makes sense, can you cook a pr?

**Comment by rvl** [comment]
Sure - #61.

Ideally direnv would show its status in the modeline, but I don't know how to do that.
