### ISSUE TITLE
Python virtualenvwrapper

### ISSUE THREAD

**Issue by behaghel** [wbolster/emacs-direnv#62]
Here is my `.envrc`:

```
layout virtualenvwrapper myenv
export TEST="test"
```

And here is what happens when I `cd` in the directory in my shell:
```
direnv: export +TEST +VIRTUAL_ENV ~PATH
```

And here is the summary that `emacs-direnv` prints when I open a buffer in the same directory:
```
direnv: +TEST (~/my/project/path)
```

Is it expected? I am trying to figure a way to get emacs to automatically use the right python version (as installed in my virtualenvs) in my projects with direnv. It works for the shell. I am unsure how much symmetry I should expect in Emacs out of the box with this package. 

Thanks.

**Comment by wbolster** [comment]
what you describe is expected, and actually the same as direnv in a shell would do. i combine this package with https://github.com/purcell/exec-path-from-shell to make sure my emacs environment is the same as in my shells, regardless of how i start emacs.

re. choosing python versions, that's something that virtualenvwrapper maybe can do for you. i stopped using that long time ago in favour of sth like `layout python-venv python 3.8` (see direnv wiki for python-venv snippet) for virtualenv management. orthogonal to that i use pyenv for installing multiple python versions on my system (in addition to operating system packages).

let me know if you want more details about my setup. pretty happy about it, and everything works both in shell and in emacs, without any manual tweaks at all.

**Comment by wbolster** [comment]
oh, missed one part of your question: seems like your virtualenvwrapper thingy fails in emacs somehow. path issues? exec-path-from-shell to r rescue.

also check the direnv buffer in emacs (see readme) since it may contain essential debugging info.

**Comment by behaghel** [comment]
Thanks, super helpful! All sorted with your guidance.

**Comment by wbolster** [comment]
cool, you're welcome. care to share what the issue was? it may help others in the future

**Comment by behaghel** [comment]
Of course, exec-path-from-shell did the trick. Also to make it work, I had to stop my shell config to automatically enter in a tmux session.

Thanks again.

**Comment by wbolster** [comment]
ah, nothing specific to virtualenvwrapper or anything like that. (good!)
