### ISSUE TITLE
emacs not recognizing jupyter?

### ISSUE THREAD

**Issue by zeta-00** [wbolster/emacs-direnv#63]
hello there, i'm using ihaskell in an isolated nix environment in emacs, and for some reason, emacs is not recognizing jupyter, i'm not sure if this has to do with emacs-direnv, but i'm just checking, here's the issues from the other repos where i posted the errors:

https://github.com/millejoh/emacs-ipython-notebook/issues/708

https://github.com/target/lorri/issues/394

**Comment by wbolster** [comment]
seems like you `PATH` is not set up properly? `(getenv "PATH")` in emacs will tell you. what's your `.envrc`; did you check the troubleshooting section in the readme? what were the results?

in short, please include minimal and complete information in your bug reports to make it easier for random strangers on the internet to actually try and help you. :)

**Comment by wbolster** [comment]
closing since no further info was provided
