### ISSUE TITLE
emacs-direnv breaks vterm prompt

### ISSUE THREAD

**Issue by ziprandom** [wbolster/emacs-direnv#66]
I'm using [emacs-libvterm](https://github.com/akermu/emacs-libvterm) and activating emacs-direnv breaks my bash prompt when I start vterm from a project that has a direnv configuration: 

```
\[\][user@host:~/direnv/project]$\[\] 
```

the prompt is configured as per README of emacs-libvterm and the error occurs even if I deactivate the direnv hook for libvterm in `.bashrc`.

**Comment by wbolster** [comment]
and what makes you think this is a `direnv.el` issue? this package only sets environment variables inside emacs, but does not interact directly with other packages.

**Comment by ziprandom** [comment]
I think this is related to `direnv.el` because the problem disappears when I disable the package in my emacs conf. I think it might be related to `direnv` altering the `PS1` or `PROMPT` env variable, but I didn't find anything suspicious there ..

**Comment by wbolster** [comment]
direnv itself does not change anything, if that's indeed the case, it stems from your own `.envrc` files somehow.

**Comment by ziprandom** [comment]
I see, it's probably connected to [lorri](https://github.com/target/lorri) then ...
