### ISSUE TITLE
Lots of these message "Invalid face reference: (diff-changed|dif-removed|diff-added)

### ISSUE THREAD

**Issue by jangid** [wbolster/emacs-direnv#69]
I get lots of these `*Messages*` when visiting first file under `direnv` control:
``` 
Invalid face reference: diff-changed
Invalid face reference: diff-removed
Invalid face reference: diff-added
Invalid face reference: diff-changed
Invalid face reference: diff-removed
Invalid face reference: diff-added
Invalid face reference: diff-changed
Invalid face reference: diff-removed
```

Is this a bug?

**Comment by cprussin** [comment]
Fix for this is to load `diff-mode` before loading `direnv-mode`, i.e. something like this if you're using `use-package`:

```elisp
(use-package direnv
  :after diff-mode
  :config (direnv-mode))
```

**Comment by wbolster** [comment]
i added `(require `diff-mode)` in 381176f

(package-lint doesn't warn about font faces, only about symbols)

**Comment by jangid** [comment]
Thanks a lot @wbolster
